### ISSUE TITLE
error during training VRCNet

### ISSUE THREAD

**Issue by MillyMaMa** [paul007pl/VRCNet#33]
Hello, thanks for your great work. However, when I train VRCNet, an error occur. Could you help me to solve this problem. Thanks!

Traceback (most recent call last):
  File "train.py", line 206, in <module>
    train()
  File "train.py", line 126, in train
    out2, loss2, net_loss = net(inputs, gt, alpha=alpha)
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/LJJ/shape_complete/ws_vrcnet/vrcnet_source/models/vrcnet.py", line 452, in forward
    o_x = self.posterior_infer2(self.posterior_infer1(feat_x))
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/LJJ/shape_complete/ws_vrcnet/vrcnet_source/models/vrcnet.py", line 97, in forward
    return self.conv2(self.af(self.conv1(self.af(feature)))) + self.conv_res(feature)
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "/data/LJJ/.conda/envs/LJJ-vrcnet/lib/python3.7/site-packages/torch/nn/functional.py", line 1297, in relu
    result = torch.relu_(input)
RuntimeError: Output 0 of SplitBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

**Comment by lk-uoser** [comment]
hello, How did you resolve it?

**Comment by MillyMaMa** [comment]
![图片1](https://github.com/paul007pl/VRCNet/assets/92417547/49ac0416-b221-42ca-a12d-e78d0badd461)
